### ISSUE TITLE
Quotes should be escaped when exporting to CSV

### ISSUE THREAD

**Issue by jenskm** [Triply-Dev/YASGUI.YASR-deprecated#87]
Variables containing quotes does not seem to get escaped when I export to CSV

The results of the following query:

```
SELECT ?var1 ?var2 ?var3
WHERE {
  BIND ("the quotes in var2 and var3 should be escaped" AS ?var1) 
  BIND ("\"surrounded by quotes\"" AS ?var2) 
  BIND (",,\"\",\",\"chaos\"\"\"" AS ?var3)   
}
```

Is exported to the following, unmanageable CSV, when I press the "Download as CSV"-button:
```
 "var1" , "var2" , "var3" ,
 "the quotes in var2 and var3 should be escaped" , ""surrounded by quotes"" , ",,"",","chaos"""" ,
```

Tested with yasr/2.9.0 + 2.11.4 AND yasr/2.10.1 + yasqe/2.11.5 and both in Chrome and Firefox

It seems to me that there is code to handle this src/jquery/tableToCsv.js, but I have not tested if this code is ever triggered.

Thank you for an excellent tool set!

Best regards,
Jens Kilde Mjelva

**Comment by LaurensRietveld** [comment]
Ah, thanks for that Jens, this should be fixed in the newest release. I'll include it in yasgui as well, after I made some other small bug fixes.

**Comment by jenskm** [comment]
Thank you for the quick response!

I still get the same output CSV (no escaped quotes) when exporting after bumping up to YASR v.2.10 locally. Same thing when testing on http://yasr.yasgui.org/.

Am I missing something?

**Comment by LaurensRietveld** [comment]
ah, was too hasty with my fix. I made some small improvements, and it should work better now

**Comment by jenskm** [comment]
Looks good!
